### ISSUE TITLE
Error on new project

### ISSUE THREAD

**Issue by andrewmcodes** [andrewmcodes/thrusters#9]
```
➜ foreman start
19:06:58 web.1     | started with pid 4032
19:06:58 webpack.1 | started with pid 4033
19:07:00 web.1     | => Booting Puma
19:07:00 web.1     | => Rails 5.2.2 application starting in development 
19:07:00 web.1     | => Run `rails server -h` for more startup options
19:07:00 webpack.1 | events.js:173
19:07:00 webpack.1 |       throw er; // Unhandled 'error' event
19:07:00 webpack.1 |       ^
19:07:00 webpack.1 | 
19:07:00 webpack.1 | Error: listen EADDRINUSE: address already in use 127.0.0.1:3035
19:07:00 webpack.1 |     at Server.setupListenHandle [as _listen2] (net.js:1254:14)
19:07:00 webpack.1 |     at listenInCluster (net.js:1302:12)
19:07:00 webpack.1 |     at GetAddrInfoReqWrap.doListen [as callback] (net.js:1441:7)
19:07:00 webpack.1 |     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:62:10)
19:07:00 webpack.1 | Emitted 'error' event at:
19:07:00 webpack.1 |     at emitErrorNT (net.js:1281:8)
19:07:00 webpack.1 |     at processTicksAndRejections (internal/process/next_tick.js:76:17)
19:07:01 webpack.1 | exited with code 1
19:07:01 system    | sending SIGTERM to all processes
19:07:01 web.1     | Exiting
19:07:01 web.1     | terminated by SIGTERM```

**Comment by andrewmcodes** [comment]
looks like this is an issue in `config/application.rb`

**Comment by andrewmcodes** [comment]
Ok so this has to do with what the app name is. It does not like if there are `_` or `-`. So the generator is not broken, but this needs to be fixed. Additionally, I still have to do a `db:reset` and `db:migrate` which I thought was fixed.
